--
-- PostgreSQL database dump
--

-- Dumped from database version 13.8 (Debian 13.8-0+deb11u1)
-- Dumped by pg_dump version 13.8 (Debian 13.8-0+deb11u1)

-- Started on 2022-11-30 05:49:21 EET

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3206 (class 0 OID 18064)
-- Dependencies: 206
-- Data for Name: defs_tables; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (715, NULL, NULL, NULL, NULL, NULL, 'cath_procedures', '<p>General Information about the Catheterization - Date Year - Operator - Procedures Performed</p>', NULL, '2016-09-14 15:57:00', '2018-05-14 13:55:01', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (928, NULL, NULL, NULL, NULL, NULL, 'pv_plasties_inflations', '<p>Pulmonary Artery Ballon Valvuloplasty Inflations</p>', NULL, '2018-10-24 13:16:31', '2018-10-24 13:16:31', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (757, NULL, NULL, NULL, NULL, NULL, 'patients', 'Patient Demographics', NULL, '2017-01-24 07:32:16', '2017-01-24 07:32:16', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (899, '<p><code></code></p>', ' 47420-5', '2.16.840.1.113883.6.1', 'LOINC:', 'FUNCTIONAL STATUS ASSESSMENT', 'functional_states', '<p>Functional Status section describes the patient''s status of normal functioning at the time the Care Record was created.&nbsp;</p>', NULL, '2017-01-08 08:59:13', '2018-10-22 14:34:09', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (919, NULL, NULL, NULL, NULL, NULL, 'proc_histories', NULL, NULL, '2018-06-08 02:51:01', '2018-06-08 02:51:01', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (742, NULL, NULL, NULL, NULL, NULL, 'infect_histories', '<p>Data Releted to Infections. HIV HBsAg etc</p>', NULL, '2016-09-14 15:57:00', '2018-10-22 14:35:45', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (783, NULL, NULL, NULL, NULL, NULL, 'discharge_meds', '<p>For Transcatheter Aortic Valve Replacement Procedures. . Discharge data as if patient had a blood transfusion and units, death</p>', NULL, '2016-09-14 15:57:00', '2018-06-12 13:13:05', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (921, NULL, NULL, NULL, NULL, NULL, 'pci_lesions_events', '<p>Any Complication - Event In Treated with PCI Lesion Inside the Cath Lab&nbsp;</p>
<p>Performation Disection etc</p>', NULL, '2018-06-28 05:18:43', '2018-06-28 05:18:43', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (922, NULL, NULL, NULL, NULL, NULL, 'pci_bifurcations', '<p>Pci For Bifurcation Lesions</p>', NULL, '2018-06-28 18:20:53', '2018-06-28 18:20:53', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (924, NULL, NULL, NULL, NULL, NULL, 'pci_ctos', '<p>PCI For Chronic Total Occlusions</p>', NULL, '2018-06-28 18:23:56', '2018-06-28 18:23:56', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (926, NULL, NULL, NULL, NULL, NULL, 'pci_fups', '<p>Follow Up For PCI Procedure.&nbsp;Follow pus mostly for coronary artery diseases. Stroke, death, readmission, cabg</p>', NULL, '2018-07-24 14:16:11', '2018-07-25 04:16:08', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (910, NULL, NULL, NULL, NULL, NULL, 'eps_history_arrhythmia', 'Arrhythmia History', NULL, '2017-03-12 09:47:05', '2017-03-12 09:47:05', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (927, NULL, NULL, NULL, NULL, NULL, 'av_plasties_inflations', '<p>Table for Inflations performed during The Aortic Valve Plasties</p>', NULL, '2018-10-20 08:30:54', '2018-10-20 08:30:54', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (923, NULL, NULL, NULL, NULL, NULL, 'pci_left_mains', '<p>PCI Files For Left Main&nbsp;</p>', NULL, '2018-06-28 18:21:44', '2018-06-28 18:21:44', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (916, NULL, NULL, NULL, NULL, NULL, 'info_coronaries', '<p>Indicate A General Information about Patient Coronaries</p>', NULL, '2018-05-15 06:31:13', '2018-05-15 06:31:13', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (917, NULL, NULL, NULL, NULL, NULL, 'cor_lesions', '<p>Table For Coronary Lesions&nbsp;</p>', NULL, '2018-05-16 13:14:38', '2018-05-16 13:14:38', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (918, NULL, NULL, NULL, NULL, NULL, 'universal', '<p>Table Conaining fields in common</p>', NULL, '2018-05-22 04:05:59', '2018-05-22 04:05:59', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (727, NULL, NULL, NULL, NULL, NULL, 'cath_grafts', '<p>For each Graft inserted we fill this table even if there is not any lesion</p>', NULL, '2016-09-14 15:57:00', '2018-05-24 01:50:19', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (911, NULL, NULL, NULL, NULL, NULL, 'eps_history_prior_therapies', 'EPS - History of Previous Therapeutic Strategies', NULL, '2017-03-14 10:37:15', '2017-03-14 10:37:15', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (896, NULL, NULL, NULL, NULL, NULL, 'eps_procs', 'Section - Table: EP/Ablation Dataset', NULL, '2017-03-15 09:48:42', '2017-03-15 09:48:42', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (874, NULL, NULL, NULL, NULL, NULL, 'nuclear_clinical', 'Clinical Information for nuclear studies', NULL, '2016-11-08 09:52:01', '2016-11-08 15:09:01', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (751, NULL, NULL, NULL, NULL, NULL, 'pace_cardiac_diagnosis', 'Specific diagnostic data for pacemakers studies. If has  brady tachy,  cardiomyopathy RV, congenital anomalies', NULL, '2017-06-30 15:10:17', '2017-06-30 15:10:17', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (686, NULL, NULL, NULL, NULL, NULL, 'acs_reperfusions', 'For patients with Acute Coronary Syndromes. The reperfusion (PCI and Lytics) data.', NULL, '2016-09-14 15:57:00', '2016-09-14 15:56:26', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (808, NULL, NULL, NULL, NULL, NULL, 'tvt_cardiac_histories', 'Transcatheter Mitral Valve Procedures â Leaflet Clip. HISTORY AND RISK FACTORS UP TO THE PROCEDURE', NULL, '2016-09-14 15:57:00', '2016-09-14 15:56:26', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (914, NULL, NULL, NULL, NULL, NULL, 'pace_post_complication', 'Post Pace procedure complications (from date of procedure to date of first follow-up)', NULL, '2017-06-30 15:22:49', '2017-06-30 15:22:49', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (885, NULL, NULL, NULL, NULL, NULL, 'nuclear_fprna_erna', 'FPRNA, first-pass radionuclide angiography; ERNA, equilibrium radionuclide angiocardiography', NULL, '2016-12-06 13:27:56', '2016-12-06 13:27:56', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (778, NULL, NULL, NULL, NULL, NULL, 'studies', 'A list of departmental Studies.', NULL, '2016-09-14 15:57:00', '2016-09-14 15:56:26', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (832, NULL, NULL, NULL, NULL, NULL, 'kccq12_questions', 'Kansas Score evaluation. All the questions', NULL, '2016-09-14 15:57:00', '2016-09-29 05:09:07', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (853, NULL, NULL, NULL, NULL, NULL, 'echo_atrial_la', 'Cardiac Echo for Left Atrium. Volumes,   Diameters, masses,', NULL, '2016-10-14 15:36:00', '2016-10-16 05:39:46', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (700, NULL, NULL, NULL, NULL, NULL, 'cardiac_echoes', 'Cardiac Echo. Administrative Data echo machine type, doctors, indications referring', NULL, '2016-09-14 15:57:00', '2016-09-24 13:47:55', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (780, NULL, NULL, NULL, NULL, NULL, 'tavr_devices', '<p>For Transcatheter Aortic Valve Replacement Procedures. DEVICE INFORMATION. Device Serial Number, Valve Sheath Access Site</p>', NULL, '2016-09-14 15:57:00', '2018-08-05 09:19:48', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (792, NULL, NULL, NULL, NULL, NULL, 'tavr_events', '<p>Transcatheter Valve Procedures: .ADVERSE EVENTS, INTERVENTIONS AND SURGICAL PROCEDURES</p>', NULL, '2016-09-14 15:57:00', '2018-08-06 04:07:08', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (844, NULL, NULL, NULL, NULL, NULL, 'echo_pericardiums', 'Echo Data of Pericardium', NULL, '2016-10-21 16:02:42', '2016-10-21 16:02:42', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (831, NULL, NULL, NULL, 'LOINC', NULL, 'aaa_fake', 'A fake section', 'templateid', '2016-10-21 16:05:51', '2016-10-21 16:05:51', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (718, NULL, NULL, NULL, NULL, NULL, 'chd_care_episodes', 'Congenital Heart Diseases. Episodes of Care. Past Medical and Surgical History, weight at birth', NULL, '2016-09-14 15:57:00', '2016-10-07 04:22:37', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (705, NULL, NULL, NULL, NULL, NULL, 'cath_clinicals', '<p>Clinical Data pre Cath</p>', NULL, '2016-09-14 15:57:00', '2018-05-29 07:05:56', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (723, NULL, NULL, NULL, NULL, NULL, 'clinical_exams', '<p>This table can be used for every day clinical Examination</p>', NULL, '2016-10-08 05:04:49', '2018-06-24 05:37:24', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (786, NULL, NULL, NULL, NULL, NULL, 'tavr_histories', '<p>For Transcatheter Aortic Valve Replacement Procedures. . HISTORY AND RISK FACTORS OTHER HISTORY AND RISK FACTORS</p>', NULL, '2016-09-14 15:57:00', '2018-08-06 06:37:07', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (879, NULL, NULL, NULL, NULL, NULL, 'nuclear_lv_perfs', 'Nuclear LV perfusion params. It contains mainly the descriptive terms of perfusion findings', NULL, '2016-11-24 06:36:15', '2016-11-24 06:36:15', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (851, NULL, NULL, NULL, NULL, NULL, 'echo_ventricle_rv', 'Echo Data for Right Ventricle', NULL, '2016-10-14 15:48:04', '2016-10-14 15:48:04', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (901, NULL, NULL, NULL, NULL, NULL, 'patient_contacts', 'A contact party (e.g. guardian, partner, friend) for the patient.', NULL, '2017-01-24 08:08:03', '2017-01-24 08:08:03', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (717, NULL, NULL, NULL, NULL, NULL, 'cath_reasons', 'A overview of reasons to do the Chatherization', NULL, '2016-09-14 15:57:00', '2016-09-28 16:43:18', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (912, NULL, NULL, NULL, NULL, NULL, 'ablation_fups', 'Ablations only Follow ups', NULL, '2017-03-15 14:49:30', '2017-03-15 14:49:30', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (737, NULL, NULL, NULL, NULL, NULL, 'discharges', 'Descriptive Patient Discharge Summary', NULL, '2017-06-26 07:59:51', '2017-06-26 07:59:51', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (770, NULL, NULL, NULL, NULL, NULL, 'pci_procedures', 'Info for PCI procedure:  Number Of Balloons Used, Device Activation Time, Device Diamters, Operators NPI', NULL, '2016-09-14 15:57:00', '2017-06-29 05:35:28', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (833, NULL, NULL, NULL, NULL, NULL, 'glossary_eps', 'Simple glossary for electophysiology studies: What is anisotropy, antidromic, refractory, lasso', NULL, '2016-10-01 04:19:37', '2016-10-01 04:19:37', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (738, NULL, NULL, NULL, NULL, NULL, 'electrocardiograms', 'Electrocardiograms:  ECG Date-Time, Findings', NULL, '2017-06-29 06:18:21', '2017-06-29 06:18:21', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (726, NULL, NULL, NULL, NULL, NULL, 'cor_anatomies', 'BEST ESTIMATE OF CORONARY ANATOMY (COMPLETE FOR EACH CATH LAB VISIT)', NULL, '2016-09-14 15:57:00', '2016-09-22 14:54:55', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (843, NULL, NULL, NULL, NULL, NULL, 'echo_pulm_arteries', 'Echo data for pulmony arteries', NULL, '2016-10-17 08:43:37', '2016-10-17 08:43:37', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (732, NULL, NULL, NULL, NULL, NULL, 'core_histories', 'Contains prior medical history. afib, angina history, family history of CAD,  Contrast allergy etc', NULL, '2016-09-14 15:57:00', '2016-09-19 13:10:40', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (849, NULL, NULL, NULL, NULL, NULL, 'echo_valve_mv', 'Cardiac Echo For Mitral Valve', NULL, '2016-10-09 08:45:27', '2016-10-19 12:14:59', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (685, NULL, NULL, NULL, NULL, NULL, 'acs_proc_tests', 'All  non invasive testing for ACS patients', NULL, '2016-10-03 08:32:37', '2016-10-03 08:32:37', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (707, NULL, NULL, NULL, NULL, NULL, 'cath_events', 'Complications After Catheterization in general', NULL, '2016-09-14 15:57:00', '2017-03-02 18:33:56', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (841, NULL, NULL, NULL, NULL, NULL, 'echo_valve_tr', 'Echo Data for Tricuspid Valve', NULL, '2016-10-19 09:47:42', '2016-10-19 09:47:42', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (807, NULL, NULL, NULL, NULL, NULL, 'treadmill_exercises', 'Table for the Standard Exercise Test', NULL, '2016-09-14 15:57:00', '2016-09-28 16:17:36', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (920, NULL, NULL, NULL, NULL, NULL, 'cath_devices', 'Hold record of cath devices', NULL, '2018-06-12 15:51:00', '2022-05-20 07:10:52', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (752, NULL, NULL, NULL, NULL, NULL, 'pace_procedure', 'Detail Data for Pacing Procedures:  antibiotics_topical,  generator_model, lead_adaptors_number', NULL, '2017-06-30 15:04:21', '2017-06-30 15:04:21', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (842, NULL, NULL, NULL, NULL, NULL, 'echo_valve_pv', 'Echo For Pulmonary Valve', NULL, '2016-10-21 14:33:40', '2016-10-21 14:33:40', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (876, NULL, NULL, NULL, NULL, NULL, 'nuclear_stresses', 'Nuclear Stress testing data. Contains changes from baseline with regard to either the ST  or onset of arrhythmias etc', NULL, '2016-11-29 07:15:16', '2016-11-29 07:15:16', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (850, NULL, NULL, NULL, NULL, NULL, 'echo_ventricle_lv', 'Data for Left Ventricular Echo', NULL, '2016-10-17 08:55:31', '2016-12-13 10:16:37', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (814, NULL, NULL, NULL, NULL, NULL, 'tmvr_proc_details', 'Transcatheter Mitral Valve Procedures â Leaflet Clip.  PROCEDURE INFORMATION', NULL, '2016-09-14 15:57:00', '2016-09-23 14:57:26', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (848, NULL, NULL, NULL, NULL, NULL, 'echo_aorta', 'The Echo for the Aorta but not for the Aortic Valve', NULL, '2016-10-23 06:37:23', '2016-10-23 06:37:23', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (882, NULL, NULL, NULL, NULL, NULL, 'nuclear_lv_rest', 'Nuclear: LV data at rest: Volumes,  EF,  Time activity Curves', NULL, '2016-11-29 08:38:33', '2016-11-29 08:38:33', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (858, NULL, NULL, NULL, NULL, NULL, 'echo_vsd', 'Echo studies for ventricular septal Defects', NULL, '2016-10-05 05:07:08', '2016-10-16 05:24:42', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (753, NULL, NULL, NULL, NULL, NULL, 'pace_re_procedures', 'Pacemaker ReProcedures Data:  pace_prior date, generator reason for action etc', NULL, '2017-06-30 12:43:20', '2017-06-30 12:43:20', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (788, NULL, NULL, NULL, NULL, NULL, 'tavr_post_evaluations', '<p>For Transcatheter Aortic Valve Replacement Procedures . POST-PROCEDURE ECHO ...</p>', NULL, '2016-09-14 15:57:00', '2018-08-08 04:34:47', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (791, NULL, NULL, NULL, NULL, NULL, 'tavr_procedures', '<p>For Transcatheter Aortic Valve Replacement Procedures. PROCEDURE INFORMATION, Operator A Name, CardioPulmonary Bypass Used,</p>', NULL, '2016-09-14 15:57:00', '2018-08-04 06:36:08', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (720, NULL, NULL, NULL, NULL, NULL, 'chd_pre_caths', '<p>Congenital Heart. Clinical and Lab Data before Cath</p>', NULL, '2016-09-14 15:57:00', '2018-08-08 13:12:49', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (708, NULL, NULL, NULL, NULL, NULL, 'cath_ffr_estimations', 'Fractional Flow Reserve data  for coronary vessels other than the PCI one''s', NULL, '2016-09-14 15:57:00', '2016-09-18 09:58:42', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (771, NULL, NULL, NULL, NULL, NULL, 'pda_procedures', 'Congenital Heart: Data For Patent Ductus Arteriosus', NULL, '2016-09-14 15:57:00', '2016-09-14 15:56:26', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (873, NULL, NULL, NULL, NULL, NULL, 'nuclear_encounter', 'Special parameters for Nuclear procedures encounters', NULL, '2016-11-08 07:23:16', '2016-11-08 07:23:16', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (884, NULL, NULL, NULL, NULL, NULL, 'nuclear_rv_parms', 'The perfusion imaging study can demonstrate perfusion data that allow interpretation of perfusion, size, and function of the right ventricle (RV). Optional', NULL, '2016-12-05 15:23:11', '2016-12-05 15:28:20', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (886, NULL, NULL, NULL, NULL, NULL, 'nuclear_viability_qual', 'Viability qualitative analysis', NULL, '2016-12-06 15:31:09', '2016-12-06 15:31:09', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (889, NULL, NULL, NULL, NULL, NULL, 'eps_history_presentation', 'For ElectroPhysiology  Studies.  Presentations Associated With Arrhythmia (Circulation. 2006;114:2534-2570.)', NULL, '2016-12-16 06:19:47', '2016-12-16 06:20:13', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (857, NULL, NULL, NULL, NULL, NULL, 'echo_mass', 'Holds the Echo Findings for Thrombus or other Masses', NULL, '2016-10-14 14:16:09', '2016-10-16 04:13:40', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (888, NULL, NULL, NULL, NULL, NULL, 'nuclear_ impressions', 'The Overall Impression assimilates all of the detailed findings presented in the prior sections into a succinct statement regarding whether LV perfusion ..etc', NULL, '2016-12-08 08:52:48', '2016-12-08 08:52:48', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (869, NULL, NULL, NULL, NULL, NULL, 'tilt_tests', 'Data Table for Tilt Tests. A tilt table test (TTT) is an inexpensive, noninvasive tool for the differential diagnosis of syncope and orthostatic intolerance and has good diagnostic yield', NULL, '2016-12-18 11:01:16', '2016-12-18 11:01:16', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (856, NULL, NULL, NULL, NULL, NULL, 'echo_valve_pros', 'Table for the Echo of the  prosthetic Valves', NULL, '2016-10-15 16:35:42', '2016-10-15 16:35:42', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (681, NULL, NULL, NULL, NULL, NULL, 'acs_hospital_events', 'Hospital Events in Acute Coronary Syndromes', NULL, '2016-09-14 15:57:00', '2016-09-21 05:03:26', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (816, NULL, NULL, NULL, NULL, NULL, 'acs_first_contacts', 'Patients with Acute Coronary Syndromes. Data concerning the status of the patient at the first medical Contact.', NULL, '2016-09-14 15:57:00', '2016-09-26 04:57:40', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (862, NULL, NULL, NULL, NULL, NULL, 'ablation_targets', 'Ablation Targets.  Collects data on the ablation target, for example indicate if the ablation target is the sinus node', NULL, '2016-11-05 15:44:04', '2016-11-05 15:46:32', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (883, NULL, NULL, NULL, NULL, NULL, 'nuclear_qualities', 'The Report It must include a statement regarding the overall quality of the study and should address the presence of potential artifacts, incidental findings, and/or extra-cardiac activity that would be pertinent to or limit the quality of the study.', NULL, '2016-12-04 09:34:53', '2016-12-04 09:35:54', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (734, NULL, NULL, NULL, NULL, NULL, 'diagnostic_codes', 'Table for the Diagnostic Codes in ICD10-CM', NULL, '2016-09-14 15:57:00', '2016-09-14 15:56:26', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (860, NULL, NULL, NULL, NULL, NULL, 'echo_atrial_septum', 'Echo of the Atrial Septum. Holds data for Atrial Septal Defect - Patent Foramen Ovale', NULL, '2016-10-14 15:17:35', '2016-10-16 06:51:22', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (892, NULL, NULL, NULL, NULL, NULL, 'eps_diagn_indications', 'Electrophysiology Studies Indications for Diagnostics', NULL, '2016-12-20 16:28:39', '2017-06-30 13:17:42', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (822, NULL, NULL, NULL, NULL, NULL, 'cad_histories', 'This table reffers to past history of acute coronary or coronay diseases', NULL, '2016-09-14 15:57:00', '2016-10-21 05:56:24', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (713, NULL, NULL, NULL, NULL, NULL, 'sat_pressures', '<p>Left and Right Heart Cath - Pressures and Saturations</p>', NULL, '2016-10-21 04:29:25', '2018-05-29 06:30:27', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (697, NULL, NULL, NULL, NULL, NULL, 'blood_samples', 'Blood Lab Results concerning the cardiac Patients', NULL, '2016-09-14 15:57:00', '2016-09-20 16:27:59', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (839, NULL, NULL, NULL, NULL, NULL, 'echo_atrial_ra', 'Echo. Data for Right Atrium', NULL, '2016-10-17 08:49:06', '2016-10-17 08:49:06', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (823, NULL, NULL, NULL, NULL, NULL, 'tavr_adj_re_interv_fups', 'For Transcatheter Aortic Valve Replacement Procedures.  J. ADJUDICATION FORM.  Event: Aortic Valve Re-intervention', NULL, '2016-09-14 15:57:00', '2016-09-28 09:28:26', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (846, NULL, NULL, NULL, NULL, NULL, 'echo_ivc', 'Echo parameters for Inferior Vena Cava', NULL, '2016-10-18 08:30:08', '2016-10-18 08:47:31', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (754, NULL, NULL, NULL, NULL, NULL, 'patient_events', 'Quick Data Summary for any adverse event. Event Date, Event Name,  Event Code', NULL, '2016-09-14 15:57:00', '2016-09-14 15:56:26', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (840, NULL, NULL, NULL, NULL, NULL, 'echo_valve_av', 'Echoes for the Aortic Valve', NULL, '2016-10-18 14:02:06', '2016-10-18 14:02:06', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (782, NULL, NULL, NULL, NULL, NULL, 'tavr_diagnostics', 'For Transcatheter Aortic Valve Replacement Procedures. DIAGNOSTIC CATH FINDINGS / ECHOCARDIOGRAM FINDINGS', NULL, '2016-09-14 15:57:00', '2016-09-20 06:24:35', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (893, NULL, NULL, NULL, NULL, NULL, 'eps_diagn_eval', 'Electrophysiology Studies:  Diagnostic Evaluations  Sinus Node Function, Atrial Function, AV Node Function', NULL, '2016-12-23 09:06:53', '2016-12-23 09:06:53', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (775, NULL, NULL, NULL, NULL, NULL, 'research_terms', 'Definitions for some research Terms: ethnicity, interventional clinical trial,  What Is Disease, The Meaning of Admssion criteria', NULL, '2016-09-14 15:57:00', '2016-09-14 15:56:26', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (802, NULL, NULL, NULL, NULL, NULL, 'tmvr_echo_fups', 'Transcatheter Mitral Valve Procedures Leaflet Clip.  FOLLOW-UP (30 Days and 1 Year) Echocardiogram', NULL, '2016-09-14 15:57:00', '2016-09-14 15:56:26', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (703, NULL, NULL, NULL, NULL, NULL, 'care_episodes', 'Table for admissions, Hospital arrival times, age', NULL, '2016-09-14 15:57:00', '2016-09-14 15:56:26', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (716, NULL, NULL, NULL, NULL, NULL, 'cath_radiations', 'Radiation data. Fluoro Karma, exposure Time,  method..of measurment', NULL, '2016-09-14 15:57:00', '2016-09-14 15:56:26', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (881, NULL, NULL, NULL, NULL, NULL, 'nuclear_lv_stress', 'Assessment of LV function and wall motion should be  performed in all patients if technically feasible with s and/or rest gated techniques', NULL, '2016-11-27 05:27:51', '2016-11-27 05:27:51', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (749, NULL, NULL, NULL, NULL, NULL, 'cor_collaterals', 'Data For Collaterals in Native  Coronary Vessels: Donor - Recipient Segment, Rendrop grade, Flow Index', NULL, '2016-09-27 06:51:17', '2018-06-03 13:01:49', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (891, NULL, NULL, NULL, NULL, NULL, 'central_meds', '<p>Section to Hold all Medications Given to the Patient</p>', NULL, '2016-12-19 09:13:30', '2018-06-12 08:47:39', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (711, NULL, NULL, NULL, NULL, NULL, 'lventricles', '<p>Data concerning the Left Ventricular Function</p>', NULL, '2016-09-14 15:57:00', '2019-09-13 14:01:24', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (760, NULL, NULL, NULL, NULL, NULL, 'pci_lesions', 'PCI: Technical as Device Used, FFR,  Lesion Length - If Previousley Treated', NULL, '2016-09-14 15:57:00', '2016-09-17 15:36:18', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (845, NULL, NULL, NULL, NULL, NULL, 'echo_svc', 'Cardiac Echo: Superior Vena Cava', NULL, '2016-10-21 08:23:53', '2016-10-21 08:23:53', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (695, NULL, NULL, NULL, NULL, NULL, 'asd_closures', 'Data for Atrial Septal Defect Interventions', NULL, '2016-09-14 15:57:00', '2016-09-15 16:02:12', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (813, NULL, NULL, NULL, NULL, NULL, 'cath_labs', '<p>PCI: Biomarkers, Creatine, Hb Before and Post Procedure</p>', NULL, '2016-09-14 15:57:00', '2018-06-14 07:13:49', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (785, NULL, NULL, NULL, NULL, NULL, 'tavr_fups', 'For Transcatheter Aortic Valve Replacement Procedures. . FOLLOW-UP (30 DAYS, 1 YEAR FROM DATE OF PROCEDURE)', NULL, '2016-09-14 15:57:00', '2016-09-21 05:28:37', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (759, NULL, NULL, NULL, NULL, NULL, 'pci_images', 'Multi Media for PCI pocedures', NULL, '2016-09-14 15:57:00', '2016-09-14 15:56:26', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (756, NULL, NULL, NULL, NULL, NULL, 'patient_proc_codes', 'Codes For patient Procedures. The Codes can be ICD10-PCS, SNOMED-CT or whatever.  Fields contained code_id, coding_system coding_date,', NULL, '2016-09-14 15:57:00', '2016-09-20 15:29:00', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (805, NULL, NULL, NULL, NULL, NULL, 'tmvr_pre_proc', 'Transcatheter Mitral Valve Procedures â Leaflet Clip.  REASONS/INDICATIONS', NULL, '2016-09-14 15:57:00', '2017-06-29 05:23:18', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (744, NULL, NULL, NULL, NULL, NULL, 'hosptal_outcomes', 'A summary Table - Section for hospital outcomes: discharge_status,  discharge_destination	, discharge_status', NULL, '2016-09-14 15:57:00', '2016-09-29 06:57:24', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (755, NULL, NULL, NULL, NULL, NULL, 'patient_in_studies', 'Studies in which  the patient is registred.  Study Name, Registred Date etc', NULL, '2016-09-14 15:57:00', '2016-09-28 12:59:35', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (887, NULL, NULL, NULL, NULL, NULL, 'nuclear_viability_quant', 'Viability quantitabe analysis:  Metabolism defect extent,  The number of 17-segment that are viable', NULL, '2016-12-08 07:26:42', '2016-12-08 07:50:59', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (829, NULL, NULL, NULL, NULL, NULL, 'tvt_adj_fups', 'Transcatheter Mitral Valve Procedures â Leaflet Clip. Adjudication Events for F/U', NULL, '2016-09-14 15:57:00', '2017-06-29 15:28:58', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (680, NULL, NULL, NULL, NULL, NULL, 'acs_discharges', 'Acute Coronary Syndromes. Discharges. Discharges File according to ncdr', NULL, '2016-09-14 15:57:00', '2016-09-21 05:49:12', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (880, NULL, NULL, NULL, NULL, NULL, 'nuclear_lv_perfs_quant', 'Nuclear LV perfusion quantitation', NULL, '2016-11-24 15:36:03', '2016-11-24 15:36:03', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (773, NULL, NULL, NULL, NULL, NULL, 'pv_plasties', 'Data For Pulmonary Valvuloplasties', NULL, '2016-09-14 15:57:00', '2016-09-16 05:26:35', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (696, NULL, NULL, NULL, NULL, NULL, 'av_plasties', 'Aortic Valve Plasties', NULL, '2016-09-14 15:57:00', '2016-09-16 05:47:13', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (746, NULL, NULL, NULL, NULL, NULL, 'icd_risk_factors', 'Risk Factors for ICD as: Sudden Death Syndromes,', NULL, '2016-09-14 15:57:00', '2016-12-11 05:53:17', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (827, NULL, NULL, NULL, NULL, NULL, 'tmvr_adj_re_interv_fups', 'Transcatheter Mitral Valve Procedures â Leaflet Clip. . ADJUDICATION FORM. If Event12000 is Mitral Valve Re-intervention', NULL, '2016-12-13 16:07:15', '2016-12-13 16:07:15', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (817, NULL, NULL, NULL, NULL, NULL, 'known_events', NULL, NULL, '2016-09-14 15:57:00', '2016-09-26 05:30:35', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (724, NULL, NULL, NULL, NULL, NULL, 'coarc_procedures', 'Data For Coarctation  Procedures.  device_type,  Pressure Gradients ...', NULL, '2016-09-14 15:57:00', '2016-09-16 13:30:27', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (895, NULL, NULL, NULL, NULL, NULL, 'eps_diagn_accessories', 'Accessory Pathway (Bypass Tract) Function. Specify number and location of accessory pathway(s).', NULL, '2016-12-27 09:42:20', '2016-12-27 09:42:20', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (689, NULL, NULL, NULL, NULL, NULL, 'admission_diagnoses', 'The Diagnostic ICD10-CM codes at episode of care', NULL, '2016-09-14 15:57:00', '2016-09-28 06:33:22', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (722, NULL, NULL, NULL, NULL, NULL, 'chd_risk_factors', 'Congenital Heart: Risk Factors as diabetes,  sickle cell anemia,  stroke prior', NULL, '2016-09-14 15:57:00', '2016-09-14 15:56:26', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (745, NULL, NULL, NULL, NULL, NULL, 'icd_care_episodes', 'Special episodes of care in patients with ICD. Admission Reason,  ICD prior type, Reason of previous ICD implantation', NULL, '2016-09-14 15:57:00', '2016-09-23 15:40:38', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (719, NULL, NULL, NULL, NULL, NULL, 'chd_procedures', '<p>Congenital Heat Diseases. Patient had Cath. Access Location, Patient Status, If intubated, trainee present</p>', NULL, '2016-09-14 15:57:00', '2018-08-08 12:58:23', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (790, NULL, NULL, NULL, NULL, NULL, 'tavr_pre_evaluations', '<p>For Transcatheter Aortic Valve Replacement Procedures. . PRE-PROCEDURE STATUS: porcelain aorta, KCCQ-12 Patient Questionnaire Performe,</p>', NULL, '2016-09-14 15:57:00', '2018-08-08 04:13:49', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (801, NULL, NULL, NULL, NULL, NULL, 'tmvr_diagnostic_caths', 'Transcatheter Mitral Valve Procedures  Leaflet Clip. Cardiac Output. The Number of diseased vessels etc are included in the Cor angio Tables', NULL, '2016-09-14 15:57:00', '2016-09-14 15:56:26', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (709, NULL, NULL, NULL, NULL, NULL, 'cath_stresses', '<p>Pre Cath Investigations mainly any investigation to detect ischemia - Test as Standard exercise test - Thallium etc</p>', NULL, '2016-09-14 15:57:00', '2018-05-29 06:26:17', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (712, NULL, NULL, NULL, NULL, NULL, 'cath_meds', '<p>Medication given during Cath. gp_iib_iiia, Vaso active drugs</p>', NULL, '2016-09-14 15:57:00', '2018-06-12 12:51:04', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (878, NULL, NULL, NULL, NULL, NULL, 'nuclear_images', 'Cardiac  Imaging parameters. Includes protocol utilized, the patient position, and radiopharmaceutical l doses administered to the patient etc', NULL, '2016-11-13 04:54:22', '2016-11-13 04:54:22', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (877, NULL, NULL, NULL, NULL, NULL, 'nuclear_ecgs', 'Nuclear ECG data: This would include the presence of any baseline ECG abnormalities that might preclude a conclusive intertaion of Stress', NULL, '2016-11-11 10:13:41', '2016-11-11 10:13:41', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (875, NULL, NULL, NULL, NULL, NULL, 'nuclear_sites', 'Nuclear Site administrative data', NULL, '2016-11-10 06:04:27', '2016-11-11 10:39:41', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (871, NULL, NULL, NULL, NULL, NULL, 'echo_stress', 'Stress Echo Table', NULL, '2016-11-08 03:18:25', '2016-11-08 03:18:25', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (900, NULL, NULL, NULL, NULL, NULL, 'utils', 'Utilities Section', NULL, '2017-02-07 15:48:42', '2017-02-07 15:48:42', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (906, NULL, NULL, NULL, NULL, NULL, 'icd_proc_info', 'ICD procedure Genreral Information', NULL, '2017-03-02 04:09:51', '2017-03-02 04:24:59', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (907, NULL, NULL, NULL, NULL, NULL, 'icd_lead_assessment', 'H. LEAD ASSESSMENT (COMPLETE FOR ALL LEADS, INCLUDING NEW LEADS IMPLANTED, EXISTING LEADS EXTRACTED, ABANDONED, OR REUSED)', NULL, '2017-03-02 07:18:16', '2017-03-02 07:18:16', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (908, NULL, NULL, NULL, NULL, NULL, 'icd_post_proc_events', 'INTRA OR POST-PROCEDURE EVENTS (COMPLETE FOR EACH LAB VISIT)', NULL, '2017-03-03 15:59:53', '2017-03-03 15:59:53', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (909, NULL, NULL, NULL, NULL, NULL, 'icd_implants', 'ICD IMPLANT / EXPLANT (COMPLETE FOR EACH LAB VISIT IN WHICH AN INITIAL GENERATOR IMPLANT, GENERATOR CHANGE, OR GENERATOR EXPLANT WAS PERFORMED)', NULL, '2017-03-04 05:39:51', '2017-03-04 05:39:51', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (804, NULL, NULL, NULL, NULL, NULL, 'tmvr_post_implant', NULL, NULL, '2016-09-14 15:57:00', '2016-10-19 07:02:15', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (913, NULL, NULL, NULL, NULL, NULL, 'pace_program', '<p>Suggested Table For Pacemaker Interrogations and programming</p>', NULL, '2017-06-30 04:08:35', '2018-05-11 13:09:53', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (809, NULL, NULL, NULL, NULL, NULL, 'tvt_fups', '<p>Transcatheter Mitral Valve Procedures: Leaflet Clip. FOLLOW-UP (30 DAYS, 1 YEAR FROM DATE OF PROCEDURE)</p>', NULL, '2016-09-14 15:57:00', '2018-05-11 17:47:53', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (683, NULL, NULL, NULL, NULL, NULL, 'acs_oral_meds', '<p>Acute Coronary Syndromes. Oral Medications</p>', NULL, '2016-09-14 15:57:00', '2018-05-29 07:01:35', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (905, NULL, NULL, NULL, NULL, NULL, 'vital_signs', '<p>Vital Signs of Patient</p>', '1.3.6.1.4.1.19376.1.4.1.5.36,', '2017-02-05 08:42:25', '2018-10-22 14:38:29', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (828, NULL, NULL, NULL, NULL, NULL, 'tmvr_adj_re_admission_fups', 'Transcatheter Mitral Valve Procedures Leaflet Clip. J. ADJUDICATION FORM If Event12000 is Readmission (Heart Failure)', NULL, '2016-12-13 15:56:12', '2019-09-04 06:28:54', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (830, NULL, NULL, NULL, NULL, NULL, 'tvt_post_implants', 'Transcatheter Mitral Valve Procedures Leaflet Clip. POST IMPLANT', NULL, '2016-09-14 15:57:00', '2019-09-04 06:29:13', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (825, NULL, NULL, NULL, NULL, NULL, 'tvt_adj_stroke_fups', 'Transcatheter Mitral Valve Procedures Leaflet Clip.  ADJUDICATION FORM. If Event is Stroke or TIA', NULL, '2016-09-14 15:57:00', '2019-09-04 06:29:32', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (929, NULL, NULL, NULL, NULL, NULL, 'proc_episodes', 'Holds Data for the Details of Coronary Angio procedure. Catheters...', NULL, '2019-09-17 04:50:32', '2019-09-17 04:50:32', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (931, NULL, NULL, NULL, NULL, NULL, 'chest_pain', 'Chest Pain Registry', NULL, '2022-05-04 17:29:44', '2022-05-04 17:29:44', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (932, NULL, NULL, NULL, NULL, NULL, 'covid', 'To select Covid-19 data', NULL, '2022-05-11 08:47:13', '2022-05-11 08:47:13', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (821, NULL, NULL, NULL, NULL, NULL, 'acs_pre_admissions', 'Acute Coronary Syndromes. All Events before Admission', NULL, '2016-09-14 15:57:00', '2022-06-04 05:31:01', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (933, NULL, NULL, NULL, NULL, NULL, 'cor_revascularization', '2020 AHA/ACC Key Data Elements and Definitions for Coronary Revascularization', NULL, '2022-05-21 07:53:14', '2022-05-21 07:53:14', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (934, NULL, NULL, NULL, NULL, NULL, 'social_histories', 'social_histories', NULL, '2022-05-21 14:58:00', '2022-05-21 14:58:00', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (682, NULL, NULL, NULL, NULL, NULL, 'acs_iv_meds', '<p>This is table belong to Acute Coronary Syndoms.</p><p>Contains the Intravenous Medications given or use during the Hospital Stay. <br /><br /></p>', NULL, '2016-09-14 15:57:00', '2022-06-02 03:29:56', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (930, NULL, NULL, NULL, NULL, NULL, 'bio_valve_dysfunc', 'Structural valve deterioration includes permanent intrinsic changes of the valve (i.e. leaflet tear, calcification, pannus eposition, flail, or fibrotic leaflet) leading to degeneration and/or dysfunction, which in turn may result in stenosis or intra-prosthetic regurgitation', NULL, '2022-05-01 15:10:49', '2022-06-13 08:36:43', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (935, NULL, NULL, NULL, NULL, 'scores', 'scores', 'Table of all scores', NULL, '2022-11-08 08:14:27', '2022-11-09 09:14:48', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (937, NULL, NULL, NULL, NULL, NULL, 'echo_terms', 'Echo Terminologies (Peak Velocity, Valve Area etc...)', NULL, '2022-11-17 15:43:35', '2022-11-17 15:43:35', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (939, NULL, NULL, NULL, NULL, NULL, 'lv_echo_diastolic_function', 'Left Ventricular Diastolic Function', NULL, '2022-11-24 08:52:35', '2022-11-24 08:52:35', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (940, NULL, NULL, NULL, NULL, 'Right Ventricular Systolic Function', 'rv_echo_systolic_function', 'Right Ventricular Systolic Function', NULL, '2022-11-25 07:14:27', '2022-11-25 07:14:27', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (941, NULL, NULL, NULL, NULL, NULL, 'rv_echo_diastolic_function', 'Left ventricular diastolic function', NULL, '2022-11-25 13:12:12', '2022-11-25 13:12:12', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (938, NULL, NULL, NULL, NULL, NULL, 'lv_echo_systolic_function', 'lv echo systolic function', NULL, '2022-11-20 08:35:05', '2022-11-29 04:11:07', NULL);
INSERT INTO public.defs_tables (id, cda_xml, code, code_system, code_system_name, display_name, name, note, template_id, inserted_at, updated_at, info_coronary_id) VALUES (721, NULL, NULL, NULL, NULL, NULL, 'chd_conditions', 'Partial List for Patient Congenital Conditions. Down, alagille, williams beuren, DiGeorge', NULL, '2016-09-14 15:57:00', '2022-11-29 04:21:53', NULL);


--
-- TOC entry 3212 (class 0 OID 0)
-- Dependencies: 205
-- Name: defs_tables_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.defs_tables_id_seq', 941, true);


-- Completed on 2022-11-30 05:49:21 EET

--
-- PostgreSQL database dump complete
--

